# Basic
title: chengshuangshuang
subtitle: chengshuangshuang's blog
description: 共同学习进步!

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 我的博客

# Navigation buttons in the front page.
nav:
    - {title: 简书, description: 简书主页, url: 'https://www.jianshu.com/u/4c385195fe52'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: chengshuangshuang
    # duoshuo: 
    
# Social
social:
    weibo: 又又又又双双
    github: cssshuang
    mail: cssshuang@sina.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

theme: jekyll-theme-cayman
